# Use the official Nginx image as a parent image
FROM nginx:alpine

# Copy the frontend files to the container at /usr/share/nginx/html
COPY templates /usr/share/nginx/html

# Expose port 80 to the world outside this container
EXPOSE 80
